config/routes.rb
Rails.application.routes.draw do
  mount InyxBlogRails::Engine, :at => '', as: 'post'
  mount InyxContactUsRails::Engine, :at => '', as: 'messages' 
  mount InyxCatalogRails::Engine, :at => '', as: 'catalog'
  root to: 'frontend#index'

  devise_for :users, skip: [:registration]

  resources :admin, only: [:index]

  scope :admin do
  	resources :users do
  		collection do
	  		post '/delete', to: 'users#delete'
  		end
  	end
  end
end

app/views/inyx_blog_rails/posts/_form.html.haml
= simple_form_for(@post) do |f|
	.container_form	
		.title_form
			Datos de del post
		.form-inyx
			- unless current_user.has_role? :moderator
				= f.input :title, label:false, input_html: { class: "form-control input-inyx", placeholder: t('post.title'), style: "margin-bottom:15px;" }
				= f.input :content, label: false, input_html: { class: "tinymce", style: "height: 200px;" }

				%div{ "ng-controller" => "formCategoryCtrl", 'ng-init'=> "#{params[:action] == 'new' ? 'init()' : "init(#{@post.category_id}, #{@post.id}, #{@post.to_json}, #{@subcategories.to_json})"}" }
					= f.association :category, label: false, collection: @categories, include_blank: "-  Categorías -", input_html: { class: "form-control input-inyx", "ng-click" => "selectAction()", "ng-model" => "post.category_id", id: "input-category" }
					%select{:name => "post[subcategory_id]", class: "form-control input-inyx", id: "input-post_subcategory_id", "ng-model"=>"obj.subcategories[selected]", "ng-options" => "subcategory.name for subcategory in obj.subcategories track by subcategory.id" }
						%option{ value: "" } - Subcategorías -
				%br
				= f.input :image, label: false, as: :file, input_html: { class: "file input-inyx", placeholder: 'image', "data-buttonBefore" => false, "data-input" => false, "data-buttonText" => params[:action] == "new" ? "Subir imágen" : "Cambiar imágen", id: "input-20" }
				%br/
				= f.input :tag_list, label: false, input_html: { class: "form-control tagsinput", placeholder: 'Tags', "data-role"=>"tagsinput", value: @post.tag_list.reverse.join(", ") }
				= f.input :public, :wrapper => :inline_checkbox
				= f.input :comments_open, :wrapper => :inline_checkbox
				= f.input :likes_enabled, :wrapper => :inline_checkbox
				= f.input :shared_enabled, :wrapper => :inline_checkbox
		.panel-footer{ style: "margin-bottom: 10px;"}
			= f.submit "Guardar", class: "btn submit-inyx pull-right"
			.clearfix

= tinymce :alternate

:javascript
	$("input[data-role=tagsinput], select[multiple][data-role=tagsinput]").tagsinput();

- if @post.image.blank?
	:javascript
		$("#input-20").fileinput({
			browseClass: "btn btn-primary btn-block",
			showCaption: false,
			showRemove: false,
			showUpload: false,
			browseIcon: '<i class="fa fa-folder-open"></i>',
			browseLabel: ' Subir imágen',
		});
- else 
	:javascript
		$("#input-20").fileinput({
			browseClass: "btn btn-primary btn-block",
			showCaption: true,
			captionIcon: '<i class="fa fa-folder-open"></i>',
			showRemove: false,
			showUpload: false,
			browseIcon: '<i class="fa fa-folder-open"></i>',
			browseLabel: ' Subir imágen',
			initialPreview: ['"#{image_tag @post.image, class: 'file-preview-image' if !@post.image.blank?}"'],
			initialCaption: " #{@post.image.file.filename.humanize}"
		});
		

app/views/inyx_blog_rails/posts/_view_lg_md.html.haml
%div{'ng-init'=>"init(#{@objects.to_json}, '/admin/blog/posts', '#{params[:search]}', #{@total_rows}, #{Kaminari.config.default_per_page})", "resize" => ""}
  .grid-content
    .col-lg-8.col-md-8{ style: "padding:0px;" } 
      .list-wrapper
        .panel.panel-default
          - flash.each do |name, msg|
            - if msg.is_a?(String)
              %div{:class => "alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'} pull-right", id: "message_alerts"}
                %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
                = content_tag :div, msg, :id => "flash_#{name}"
          .panel-heading#list-heading{ style: "width:67%;"}
            - if can? :new, InyxBlogRails::Post
              = link_to new_post_path, class: "btn btn-default btn-action", title: t("admin.buttons.new") do
                %i.fa.fa-plus-circle
            - if can? :new, InyxBlogRails::Category
              = link_to new_category_path, class: "btn btn-default btn-action", title: "Añadir categoría" do
                %i.fa.fa-tags
            %a.btn.btn-default.btn-action{"ng-click" => "refresh()", "ng-disabled" => "pagesItemsSelected[currentPageServer].length != 0", :title => t("admin.buttons.refresh") }
              %i.fa.fa-refresh#icon-refresh{'ng-show'=>"!loadingRefresh"}
              %i.fa.fa-refresh.fa-spin{'ng-show'=>"loadingRefresh"}
            - if can? :delete, InyxBlogRails::Post
              %a.btn.btn-default.btn-action{"ng-show" => "objects.length", "ng-click" => "allSelected(objects)", :title => t("admin.buttons.select_all") }
                %i.fa.fa-square-o{"ng-show" => "!btnDelete"}
                %i.fa.fa-check-square-o{ "ng-show" => "btnDelete" } 
            - if can? :delete, InyxBlogRails::Post
              %a.btn.btn-default.btn-action#btn-delete{ "ng-show" => "btnDelete", "ng-click" => "destroy('¿Estas seguro de querer eliminar los posts seleccioandos?')", :title => t("admin.buttons.trash") }
                %i.fa.fa-circle-o-notch.fa-spin{ 'ng-show' => "loadingDelete" }
                %i.fa.fa-trash-o{ 'ng-show' => "!loadingDelete" }
            .paginator.pull-right{ "ng-show" => "objects.length > 0"}
              %button.btn.btn-default.pull-right.hidden-xs{'disabled'=>"", style:"color:#000; margin-left:3px;"}
                Página {{currentPage+1}} de {{numberOfPages()}}
              %a.btn.btn-default.pull-right.next{ "ng-disabled"=>"currentPage >= total_objects/pageSize - 1 || loadingNext", "ng-click"=>"next()", style: "margin-left:3px" }
                %i.fa.fa-circle-o-notch.fa-spin{ 'ng-show' => "loadingNext" }
                %i.fa.fa-arrow-right{ 'ng-show' => "!loadingNext" }
              %a.btn.btn-default.pull-right.last{'ng-disabled'=>"currentPage == 0 || loadingLast", "ng-click"=>"last()"}
                %i.fa.fa-circle-o-notch.fa-spin{ 'ng-show' => "loadingLast" }
                %i.fa.fa-arrow-left{ 'ng-show' => "!loadingLast" }
          .panel-body{ style: "border-right: 1px solid #e7e7e7;" }
            #table-scroll
              %table.grid{style: "width:100%"}
                %tbody
                  %tr{ class: "select-{{object.checked}}", "ng-click" => "show_object(object)", :id => "row-{{object.id}}", "ng-repeat" => "object in objects | startFrom:currentPage*pageSize | limitTo:pageSize" }
                    - if can? :delete, InyxBlogRails::Post
                      %td{ width: "1px;" }
                        .checkboxFour
                          %input.checkboxFourInput{:id => "check-{{object.id}}", :type => "checkbox", "ng-model" => "object.checked", "ng-click" => "selected(object); $event.stopPorpagation();" }
                          %label{ for: "check-{{object.id}}" }
                            %span
                    %td {{ object.title_truncate }}
                    %td {{ object.autor }}
                    %td {{ object.category_name }}
                    %td {{ object.public }}


  .col-lg-4.col-md-4{ style: "padding:0px;"}
    .show-wrapper
      .show-head
      .show-body{ style: "position: fixed; width:33.3%;"}
        .panel.panel-default
          .panel-heading{ style: "height:55px;" }
            .actions{ "ng-show" => "object_data" }
              .title.pull-left{ style: "margin-top:6px;" }
                %i.fa.fa-pencil
                Post - {{ object_data.id }}
              - if can? :destroy, InyxBlogRails::Post
                = link_to "{{destroy_path(object_data.id)}}", title: t('admin.actions.delete'), :method => :delete, :data => { :confirm => '¿Estas seguro de querer eliminar este post?' }, class: "btn btn-default btn-action pull-right", "ng-show" => "object_data" do
                  %i.fa.fa-remove
              - if can? :edit, InyxBlogRails::Post
                = link_to "{{edit_path(object_data.id)}}", title: t('admin.actions.edit'), class: "btn btn-default btn-action pull-right", "ng-show" => "object_data", style: "margin-right:3px;" do
                  %i.fa.fa-pencil
              = link_to "/blog/posts/{{object_data.permalink}}", title: "Ver en la web", class: "btn btn-default btn-action pull-right", "ng-show" => "object_data", style: "margin-right:3px;", target: "_blank" do
                %i.fa.fa-eye
            .no-actions{ "ng-show" => "!object_data", style: "margin-top:6px;" }
              %i.fa.fa-pencil
              Post
          .panel-body{ 'ng-controller'=>'frontIndexCtrl' }
            .data{ style: "height: {{windowHeight-104}}px;" }
              %img{ "ng-show" => "object_data.image", "ng-src" => "{{object_data.image}}", alt: "{{posts.title}}", title: "{{posts.title}}" }
              .attributes{ "ng-show" => "object_data" }
                %label Título: 
                {{object_data.title}}
                %br/
                %label Autor: 
                {{object_data.autor | titlecase }}
                %br/
                %label Categoría: 
                {{object_data.category_name}}
                %br/
                %label Subcategoría: 
                {{object_data.subcategory_name}}
                %br/
                %label ¿Publicado?:
                {{object_data.public}}
                %br/
                %label Permalink:
                {{object_data.permalink}}
                %br/
                %label Creado:
                {{object_data.created_at | date : format : timezone}}
                %br/
                %label Modificado:
                {{object_data.updated_at | date : format : timezone}}
                %br/
                %label Contenido:
                .panel.panel-warning{"ng-bind-html" => "content_html(object_data.content)", style: 'margin-top:10px; padding: 10px; border-color: #4758d3; border-radius:0px; text-align:justify;' }
                %br/
              .no-data{ "ng-show" => "!object_data"}
                %center
                  No se ha seleccionado un post para mostrar.
      .show-footer

app/views/inyx_blog_rails/posts/_view_sm_xs.html.haml
- if can? :new, InyxBlogRails::Post
	= link_to new_post_path, class: "float-button" do
		%i.fa.fa-plus
.panel.panel-default{style:"margin-top:50px"}
	.panel-header
		.paginator{ "ng-show" => "objects.length > 0"}
			%center
				Página {{currentPage+1}} de {{numberOfPages()}}
			%a.btn.btn-default.next{ "ng-disabled"=>"currentPage >= total_objects/pageSize - 1 || loadingNext", "ng-click"=>"next()", style: "margin-left:3px" }
				%i.fa.fa-circle-o-notch.fa-spin{ 'ng-show' => "loadingNext" }
				%i.fa.fa-arrow-right{ 'ng-show' => "!loadingNext" }
			%a.btn.btn-default.last{'ng-disabled'=>"currentPage == 0 || loadingLast", "ng-click"=>"last()"}
				%i.fa.fa-circle-o-notch.fa-spin{ 'ng-show' => "loadingLast" }
				%i.fa.fa-arrow-left{ 'ng-show' => "!loadingLast" }
	.panel-body#grid{ style: "border-right: 1px solid #e7e7e7;padding-left: 0px;padding-right: 0px;border-top-width: 36px;" }	
		%table.grid{style: "width:100%;"}
			%tbody
				%tr{ class: "select-{{object.checked}}", "ng-click" => "show_object(object)", :id => "row-{{object.id}}", "ng-repeat" => "object in objects | startFrom:currentPage*pageSize | limitTo:pageSize"}
					- if can? :delete, InyxBlogRails::Post
						%td{ width: "1px;" }
							.checkboxFour
								%input.checkboxFourInput{:id => "check-{{object.id}}", :type => "checkbox", "ng-model" => "object.checked", "ng-click" => "selected(object); $event.stopPorpagation();" }
								%label{ for: "check-{{object.id}}" }
									%span
					%td{ style: "text-align:left;" }
						= link_to "{{show_path(object.id)}}", style: "width:100%;" do
							{{ object.title }}
				%tr{"ng-show" => "!objects.length"}
					%td{:style => "width:100%"}
						%center
							%i.fa.fa-frown-o
							No hay Posts.

app/views/inyx_blog_rails/posts/autor_front.html.haml
= content_for(:title, "Blog - #{params[:permalink].humanize.gsub("-", " ")}")
.container
	.row.blog{'ng-controller'=>'frontIndexCtrl', 'ng-init'=>"init(#{@posts.to_json})", "when-scrolled" => "loadMore()" }
		= render "layouts/inyx_blog_rails/blog/sidebar_left"
		= render "layouts/inyx_blog_rails/blog/posts_list"

app/views/inyx_blog_rails/posts/category_front.html.haml
= content_for(:title, "Blog - #{params[:category_permalink].humanize.gsub("-", " ")}")
.blog
	.container
		.row{'ng-controller'=>'frontIndexCtrl', 'ng-init'=>"init(#{@posts.to_json})", "when-scrolled" => "loadMore()" }
			= render "layouts/inyx_blog_rails/blog/navbar_categories"
			= render "layouts/inyx_blog_rails/blog/sidebar_left"
			= render "layouts/inyx_blog_rails/blog/posts_list"

app/views/inyx_blog_rails/posts/edit.html.haml
= content_for(:title, "Admin - Post | Editar")
%div{ style: "padding:10px; padding-bottom:0px;"}
	= render 'form'

app/views/inyx_blog_rails/posts/index.html.haml
= content_for(:title, "Admin - Posts")

.view-lg-md.hidden-xs.hidden-sm
  = render "view_lg_md"
.view-sm-xs.hidden-lg.hidden-md
  = render "view_sm_xs"

app/views/inyx_blog_rails/posts/index_front.html.haml
= content_for(:title, "Blog - Posts") 
.container
	.row.blog{'ng-controller'=>'frontIndexCtrl', 'ng-init'=>"init(#{@posts.to_json})", "when-scrolled" => "loadMore()" }

		= render "layouts/inyx_blog_rails/blog/navbar_categories"
		= render "layouts/inyx_blog_rails/blog/sidebar_left"
		.hidden-lg.hidden-md{ style: "padding: 0px 10px 0px 10px;"}
			= render "inyx_blog_rails/posts/widgets/search"
		= render "layouts/inyx_blog_rails/blog/posts_list"	

	

		

app/views/inyx_blog_rails/posts/new.html.haml
= content_for(:title, "Admin - Post | Nuevo")
%div{ style: "padding:10px; padding-bottom:0px;"}
	= render 'form'

app/views/inyx_blog_rails/posts/search.html.haml
= content_for(:title, "Blog - Posts - Search")
.container
	.row.blog{'ng-controller'=>'frontIndexCtrl', 'ng-init'=>"init(#{@posts.to_json})", "when-scrolled" => "loadMore()" }
		= render "layouts/inyx_blog_rails/blog/navbar_categories"
		= render "layouts/inyx_blog_rails/blog/sidebar_left"
		= render "layouts/inyx_blog_rails/blog/posts_list"

app/views/inyx_blog_rails/posts/show.html.haml
= content_for(:title, "Admin - Post | #{@post.title}")
%div#show-mobile-post
	= render "layouts/admin/messages"
	.panel.panel-default{style:"margin-top:50px"}
		.panel-heading#heading-show{ style: "padding-top:5px;"}
			.actions
				.title.pull-left{ style: "margin-top:8px;" }
					%i.fa.fa-pencil
					Post - 
					= @post.id
				- if can? :destroy, InyxBlogRails::Post
					= link_to post_path(@post), title: t('admin.actions.delete'), :method => :delete, :data => { :confirm => '¿Estas seguro de querer eliminar este usuario?' }, class: "btn btn-default btn-action pull-right" do
						%i.fa.fa-remove
				- if can? :edit, InyxBlogRails::Post
					= link_to edit_post_path(@post), title: t('admin.actions.edit'), class: "btn btn-default btn-action pull-right", style: "margin-right:3px;" do
						%i.fa.fa-pencil		
		
		- unless @post.image.blank?
			= image_tag @post.image, style: "width:100%", class: "hidden-lg hidden-md"
			= image_tag @post.image, style: "width:50%; margin-top:10px; margin-bottom:0px;", class: "thumbnail hidden-xs hidden-sm"
		- else
			%center{ style: "margin-top: 10px;" }
				%p{ style: "margin-bottom:0px;"} Sin imagen
		.panel-body#body-show
			%label= t('post.title')+': '
			= @post.title.humanize
			%br/
			%label= t('post.autor')+': '
			= @post.user.name
			%br/
			%label= t('post.category')+': '
			= @post.category.name
			%br/
			%label= t('post.subcategory')+': '
			= @post.subcategory.nil? ? "Sin subcategoría" : @post.subcategory.name
			%br/
			%label= t('post.permalink')+': '
			= @post.permalink
			%br/
			.panel.panel-warning{ style: 'margin-top:10px; padding: 10px; border-color: #4758d3; border-radius:0px;'}
				.panel-body
					= raw @post.content
			.row{ style: 'margin: 0px; margin-top:10px;'}
				.col-lg-3.col-md-3.col-sm-12
					%label= t('post.public')+': '
					= @post.public ? "<i class='fa fa-check-circle' style='color:#FFBA3D; font-size:20px;'></i>".html_safe : "<i class='fa fa-minus-circle' style='color:#d9534f; font-size:20px;'></i>".html_safe
				.col-lg-3.col-md-3.col-sm-12
					%label= t('post.comments_open')+': '
					= @post.comments_open ? "<i class='fa fa-check-circle' style='color:#FFBA3D; font-size:20px;'></i>".html_safe : "<i class='fa fa-minus-circle' style='color:#d9534f; font-size:20px;'></i>".html_safe
				.col-lg-3.col-md-3.col-sm-12
					%label= t('post.likes_enabled')+': '
					= @post.likes_enabled ? "<i class='fa fa-check-circle' style='color:#FFBA3D; font-size:20px;'></i>".html_safe : "<i class='fa fa-minus-circle' style='color:#d9534f; font-size:20px;'></i>".html_safe
				.col-lg-3.col-md-3.col-sm-12
					%label= t('post.shared_enabled')+': '
					= @post.shared_enabled ? "<i class='fa fa-check-circle' style='color:#FFBA3D; font-size:20px;'></i>".html_safe : "<i class='fa fa-minus-circle' style='color:#d9534f; font-size:20px;'></i>".html_safe
			%br/
			%label= t('post.tags')+': '
			- @post.tag_list.each do |tag|
				%span.label-tag= tag

app/views/inyx_blog_rails/posts/show_front.html.haml
= content_for(:title, "Blog - #{@post.title}")
= content_for(:description, strip_tags(@post.content).truncate(180))
.container
	.row.blog{'ng-controller'=>'frontIndexCtrl', 'ng-init'=>"init(#{@post.to_json})"}
		= render "layouts/inyx_blog_rails/blog/navbar_categories"
		= render "layouts/inyx_blog_rails/blog/sidebar_left"
		= render "layouts/inyx_blog_rails/blog/post"

app/views/inyx_blog_rails/posts/subcategory_front.html.haml
= content_for(:title, "Blog - #{params[:subcategory_permalink].humanize.gsub("-", " ")}")
.blog
	.container
		.row{'ng-controller'=>'frontIndexCtrl', 'ng-init'=>"init(#{@posts.to_json})", "when-scrolled" => "loadMore()" }
			= render "layouts/inyx_blog_rails/blog/navbar_categories"
			= render "layouts/inyx_blog_rails/blog/sidebar_left"
			= render "layouts/inyx_blog_rails/blog/posts_list"

app/views/inyx_blog_rails/posts/tag_front.html.haml
= content_for(:title, "Blog - #{params[:permalink].humanize.gsub("-", " ")}")
.container
	.row.blog{'ng-controller'=>'frontIndexCtrl', 'ng-init'=>"init(#{@posts.to_json})" }
		= render "layouts/inyx_blog_rails/blog/navbar_categories"
		= render "layouts/inyx_blog_rails/blog/sidebar_left"
		= render "layouts/inyx_blog_rails/blog/posts_list"